export const REQUEST_SKILLS = 'REQUEST_SKILLS';
export const RECEIVE_SKILLS = 'RECEIVE_SKILLS';
export const UPDATE_SKILLS_AJAX_STATUS = 'UPDATE_SKILLS_AJAX_STATUS';
export const requestSkills = () => ({ type: REQUEST_SKILLS });

export const REQUEST_EXPERIENCE = 'REQUEST_EXPERIENCE';
export const RECEIVE_EXPERIENCE = 'RECEIVE_EXPERIENCE';
export const UPDATE_EXPERIENCE_AJAX_STATUS = 'UPDATE_EXPERIENCE_AJAX_STATUS';
export const requestExperience = () => ({ type: REQUEST_EXPERIENCE });

export const REQUEST_EDUCATION = 'REQUEST_EDUCATION';
export const RECEIVE_EDUCATION = 'RECEIVE_EDUCATION';
export const UPDATE_EDUCATION_AJAX_STATUS = 'UPDATE_EDUCATION_AJAX_STATUS';
export const requestEducation = () => ({ type: REQUEST_EDUCATION });

export const REQUEST_PORTFOLIO = 'REQUEST_PORTFOLIO';
export const RECEIVE_PORTFOLIO = 'RECEIVE_PORTFOLIO';
export const UPDATE_PORTFOLIO_AJAX_STATUS = 'UPDATE_PORTFOLIO_AJAX_STATUS';
export const requestPortfolio = () => ({ type: REQUEST_PORTFOLIO });
